### ISSUE TITLE
Error line number

### ISSUE THREAD

**Issue by reggi** [reggi/evalmd#3]
Because markdown is stripped the line number the error occurs on is the raw contacted js and not accurate. Need to flood `code` with empty lines to fix.

```
thomas@workstation:node-reggi$ evalmd ./docs/dep-obj-parsing.md

assert.js:89
  throw new assert.AssertionError({
        ^
Unhandled rejection AssertionError: [ '' ] deepEqual [ 'alpha' ]
    at ./docs/dep-obj-parsing.md:96:8
    at ContextifyScript.Script.runInNewContext (vm.js:18:15)
    at module.exports (/Users/thomas/.nvm/versions/io.js/v2.5.0/lib/node_modules/evalmd/node_modules/eval/eval.js:56:8)
    at /Users/thomas/.nvm/versions/io.js/v2.5.0/lib/node_modules/evalmd/test-markdown.js:58:7
    at tryCatcher (/Users/thomas/.nvm/versions/io.js/v2.5.0/lib/node_modules/evalmd/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/thomas/.nvm/versions/io.js/v2.5.0/lib/node_modules/evalmd/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/Users/thomas/.nvm/versions/io.js/v2.5.0/lib/node_modules/evalmd/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/Users/thomas/.nvm/versions/io.js/v2.5.0/lib/node_modules/evalmd/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/Users/thomas/.nvm/versions/io.js/v2.5.0/lib/node_modules/evalmd/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/thomas/.nvm/versions/io.js/v2.5.0/lib/node_modules/evalmd/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/thomas/.nvm/versions/io.js/v2.5.0/lib/node_modules/evalmd/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```

**Comment by reggi** [comment]
https://github.com/reggi/evalmd/commit/692d3f4e067d4691819554ea3ae13806505cd9e5
